server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/uap
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin123456!@#
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka